### PR TITLE
Update labo_train.sh

### PR DESCRIPTION
**Pull request by Wazhee**
In labo_train.sh you defined "cfg/asso_opt/$2/$2_$1shot_fac.py" as the config filepath.

If $1 is {Dataset} & $2 is {shots} as defined in the readme, the labo_train.sh should be defined as the following:

cfg/asso_opt/$1/$1_$2shot_fac.py

### CODE REVIEW

**Comment by YueYANG1996** [comment]
Thanks for updating this! I just updated the readme to fix this.

**Comment by Wazhee** [comment]
Can you send me your filtered concepts for cifar10 and Ham10000 dataset?

Best,
Jason

**Comment by YueYANG1996** [comment]
How many concepts do you need for each class?

**Comment by Wazhee** [comment]
I don’t remember what was the optimal number of concept mentioned in the
paper. However i would like the opportunity recreate the best results, 87.9
i believe.

**Comment by YueYANG1996** [comment]
Sorry for the late reply, please see the data here: https://github.com/YueYANG1996/LaBo/tree/main/selected_concepts

**Pull request closed without merging**
